-- CREATE TABLE person (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50), age SMALLINT UNSIGNED)
-- CREATE TABLE Test (id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, name VARCHAR(50) NOT NULL, created DATETIME NOT NULL, gender ENUM('M', 'F', 'O') NOT NULL)

-- DESCRIBE person

-- INSERT INTO person (name, age) VALUES ("Sayed", 25)

-- ALTER TABLE Test ADD COLUMN food VARCHAR(50) NOT NULL